### ISSUE TITLE
Use prepared statement instead of string concatenation

### ISSUE THREAD

**Issue by navneetkarnani** [DNV4912/Calendar-App#2]
https://github.com/DNV4912/Calendar-App/blob/f37eeca1872d08b8d731634bcac0edf7c0dd6b02/generate_ics.py#L28

Ref:
https://stackoverflow.com/questions/433392/how-do-i-use-prepared-statements-in-sqlite-in-android

**Comment by DNV4912** [comment]
Changes have been made
